config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  root 'welcome_pages#index'

  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
	validates :car_name, presence: true
	validates :car_type, presence: true
	
	validates :car_price, presence: true

	belongs_to :owner
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
	before_action :set_car_id, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_owner!, except: :index
	
	def index
		@cars = Car.all
	end

	def new
		@car = current_owner.cars.new
	end

	def create
		@car = current_owner.cars.create(car_params)

		if @car.save
			flash[:message] = "Done"
			redirect_to cars_url
		else
			render :new
		end
	end

	def show
	end

	def edit
	end

	def update
		if current_owner.cars.update(car_params)
			flash[:message] = "Done"
			redirect_to car_url(@car)
		else
			render :edit
		end
	end

	def destroy
		current_owner.cars.destroy
		redirect_to cars_url
	end

	private

	def set_car_id
		@car = current_owner.cars.find_by(id: params[:id])
	end

	def car_params
		params.require(:car).permit(:car_type, :car_name, :car_years, :car_price)
	end
end

app/controllers/welcome_pages_controller.rb
class WelcomePagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/welcome_pages_helper.rb
module WelcomePagesHelper
end

app/views/cars/edit.html.erb
<div>
	<h1>
		Update Current Rental Car
	</h1>
	<%= render 'partials/form' %>
</div>

app/views/cars/index.html.erb
<div>
	<header>
		<h1>Car rentals list</h1>
	</header>
	<div>
		<%= link_to 'New', new_car_path %>
	</div>
	<div>
		<% @cars.each do |car| %>
		<ul>
			<li>
				<header>
					<h3><%= link_to car.car_name, car_path(car) %></h3>
				</header>
				<ul>
					<li><%= car.car_type %></li>
					<li><%= car.car_years %></li>
					<li><%= number_to_currency(car.car_price) %></li>
				</ul>
			</li>
		</ul>
		<% end %>
	</div>
</div>

app/views/cars/new.html.erb
<div>
	<h1>
		Add New Rental Car
	</h1>
	<%= render 'partials/form' %>
</div>

app/views/cars/show.html.erb
<div>
	<h1>
		<%= @car.car_name %> Information
	</h1>
	<div>
		<ul>
			<li>
				Year makes: <%= @car.car_years %>
			</li>
			<li>
				Type: <%= @car.car_type %>
			</li>
			<li>
				Rental Price: <%= number_to_currency(@car.car_price) %>
			</li>
		</ul>
		<div>
			<%= link_to 'Edit', edit_car_path(@car) %> | <%= link_to 'Delete', car_url(@car), method: :delete, data: {confirm: "Are you sure want to delete #{@car.car_name}?"} %> | <%= link_to 'Back', cars_url %>
		</div>
	</div>
</div>

app/views/layouts/_alert.html.erb
<% if object.errors.any? %>
	<div class="alert alert-danger" id="error_explanation">
		<h2>
			<%= pluralize(object.errors.count, "error") %> prohibited this data from being saved:
			<ul>
				<% object.errors.full_messages.each do |msg| %>
				<li>
					<%= msg %>
				</li>
				<% end %>
			</ul>
		</h2>
	</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
	<ul>
		<% if current_owner %>
			<li><%= current_owner.email %></li>
			<li><%= link_to 'Sign Out', destroy_owner_session_path, method: :delete %></li>
		<% else %>
			<li><%= link_to 'Sign Up', new_owner_registration_path %></li>
			<li><%= link_to 'Sign In', new_owner_session_path %></li>
		<% end %>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InterviewApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navbar' %>
  	<% if notice %>
	  	<p class="notice"><%= notice %></p>
  	<% else %>
	  	<p class="alert"><%= alert %></p>
  	<% end %>
    <%= yield %>
  </body>
</html>

app/views/partials/_form.html.erb
<%= render 'layouts/alert', object: @car%>
<%= form_with model: @car do |form| %>
	<div>
		<div>
			<%= form.label :car_name  %>
			<%= form.text_field :car_name %>
		</div>
		<div>
			<%= form.label :car_type  %>
			<%= form.text_field :car_type %>
		</div>
		<div>
			<%= form.label :car_years %>
			<%= form.text_field :car_years %>
		</div>
		<div>
			<%= form.label :car_price %>
			<%= form.text_field :car_price %>
		</div>
		<div>
			<%= form.submit "Save" %>
		</div>
	</div>
<% end %>

app/views/welcome_pages/index.html.erb
<!-- jumbo div -->
<div class="container">
	<header>
		<h1>
			Welcome to the rental vehicle page, where you can rent your favorite car with the trusted dealer.
		</h1>
	</header>
	<div>
		<%= link_to 'Car Rentals List', cars_url %>
	</div>
</div>